module.exports = {
    DEFAULT_ARRIVALS_AND_DEPARTURES_FOR_STOP_RESPONSE: {
        code: 200,
        currentTime: 1577645856024,
        data: {
            entry: {
                arrivalsAndDepartures: [
                    {
                        arrivalEnabled: true,
                        blockTripSequence: 10,
                        departureEnabled: true,
                        distanceFromStop: 3903.8898214878136,
                        frequency: null,
                        historicalOccupancy: '',
                        lastUpdateTime: 1577645785000,
                        numberOfStopsAway: 16,
                        predicted: true,
                        predictedArrivalInterval: null,
                        predictedArrivalTime: 1577646516000,
                        predictedDepartureInterval: null,
                        predictedDepartureTime: 1577646516000,
                        predictedOccupancy: '',
                        routeId: '1_100009',
                        routeLongName: '',
                        routeShortName: '11',
                        scheduledArrivalInterval: null,
                        scheduledArrivalTime: 1577646516000,
                        scheduledDepartureInterval: null,
                        scheduledDepartureTime: 1577646516000,
                        serviceDate: 1577606400000,
                        situationIds: [],
                        status: 'default',
                        stopId: '1_12353',
                        stopSequence: 15,
                        totalStopsInTrip: 24,
                        tripHeadsign: 'Downtown Seattle Via E Madison St',
                        tripId: '1_40552711',
                        tripStatus: {
                            activeTripId: '1_40552671',
                            blockTripSequence: 9,
                            closestStop: '1_12480',
                            closestStopTimeOffset: -1,
                            distanceAlongTrip: 7127.686348762625,
                            frequency: null,
                            lastKnownDistanceAlongTrip: 0,
                            lastKnownLocation: {
                                lat: 47.63910675048828,
                                lon: -122.27708435058594,
                            },
                            lastKnownOrientation: 0,
                            lastLocationUpdateTime: 1577645785000,
                            lastUpdateTime: 1577645785000,
                            nextStop: '1_12210',
                            nextStopTimeOffset: 28,
                            orientation: 89.45982952240779,
                            phase: 'in_progress',
                            position: {
                                lat: 47.63916701771526,
                                lon: -122.27708343415102,
                            },
                            predicted: true,
                            scheduleDeviation: 713,
                            scheduledDistanceAlongTrip: 7127.686348762625,
                            serviceDate: 1577606400000,
                            situationIds: [],
                            status: 'SCHEDULED',
                            totalDistanceAlongTrip: 7376.834593544655,
                            vehicleId: '1_7107',
                        },
                        vehicleId: '1_7107',
                    },
                    {
                        arrivalEnabled: true,
                        blockTripSequence: 10,
                        departureEnabled: true,
                        distanceFromStop: 1722.6094902976765,
                        frequency: null,
                        historicalOccupancy: '',
                        lastUpdateTime: 1577645810000,
                        numberOfStopsAway: 8,
                        predicted: true,
                        predictedArrivalInterval: null,
                        predictedArrivalTime: 1577647418000,
                        predictedDepartureInterval: null,
                        predictedDepartureTime: 1577647418000,
                        predictedOccupancy: '',
                        routeId: '1_100018',
                        routeLongName: '',
                        routeShortName: '12',
                        scheduledArrivalInterval: null,
                        scheduledArrivalTime: 1577646957000,
                        scheduledDepartureInterval: null,
                        scheduledDepartureTime: 1577646957000,
                        serviceDate: 1577606400000,
                        situationIds: [],
                        status: 'default',
                        stopId: '1_12353',
                        stopSequence: 8,
                        totalStopsInTrip: 19,
                        tripHeadsign: 'Downtown Seattle Madison St',
                        tripId: '1_44249598',
                        tripStatus: {
                            activeTripId: '1_44249598',
                            blockTripSequence: 10,
                            closestStop: '1_13200',
                            closestStopTimeOffset: -9,
                            distanceAlongTrip: 3.6863509012619033e-4,
                            frequency: null,
                            lastKnownDistanceAlongTrip: 0,
                            lastKnownLocation: {
                                lat: 47.631893157958984,
                                lon: -122.30723571777344,
                            },
                            lastKnownOrientation: 0,
                            lastLocationUpdateTime: 1577645810000,
                            lastUpdateTime: 1577645810000,
                            nextStop: '1_13200',
                            nextStopTimeOffset: 1311,
                            orientation: 269.3296431543369,
                            phase: 'in_progress',
                            position: {
                                lat: 47.631896996684894,
                                lon: -122.30723600003878,
                            },
                            predicted: true,
                            scheduleDeviation: 461,
                            scheduledDistanceAlongTrip: 3.6863509012619033e-4,
                            serviceDate: 1577606400000,
                            situationIds: [],
                            status: 'SCHEDULED',
                            totalDistanceAlongTrip: 4108.603541578358,
                            vehicleId: '1_7057',
                        },
                        vehicleId: '1_7057',
                    },
                ],
                nearbyStopIds: ['1_12373', '1_13300'],
                situationIds: [],
                stopId: '1_12353',
            },
            references: {
                agencies: [
                    {
                        disclaimer: '',
                        email: '',
                        fareUrl:
                            'http://metro.kingcounty.gov/tops/bus/fare/fare-info.html#fare_matrix',
                        id: '1',
                        lang: 'EN',
                        name: 'Metro Transit',
                        phone: '206-553-3000',
                        privateService: false,
                        timezone: 'America/Los_Angeles',
                        url: 'http://metro.kingcounty.gov',
                    },
                ],
                routes: [
                    {
                        agencyId: '1',
                        color: '',
                        description:
                            'Madison Park - Capitol Hill - Downtown Seattle',
                        id: '1_100009',
                        longName: '',
                        shortName: '11',
                        textColor: '',
                        type: 3,
                        url:
                            'http://metro.kingcounty.gov/schedules/011/n0.html',
                    },
                    {
                        agencyId: '1',
                        color: '',
                        description:
                            'Interlaken Park - First Hill - Downtown Seattle',
                        id: '1_100018',
                        longName: '',
                        shortName: '12',
                        textColor: '',
                        type: 3,
                        url:
                            'http://metro.kingcounty.gov/schedules/012/n0.html',
                    },
                ],
                situations: [],
                stops: [
                    {
                        code: '12353',
                        direction: 'SW',
                        id: '1_12353',
                        lat: 47.616619,
                        locationType: 0,
                        lon: -122.307877,
                        name: 'E Madison St & 19th Ave',
                        routeIds: ['1_100009', '1_100018'],
                        wheelchairBoarding: 'UNKNOWN',
                    },
                    {
                        code: '12480',
                        direction: 'N',
                        id: '1_12480',
                        lat: 47.639088,
                        locationType: 0,
                        lon: -122.276993,
                        name: '43rd Ave E & E Lynn St',
                        routeIds: ['1_100009'],
                        wheelchairBoarding: 'UNKNOWN',
                    },
                    {
                        code: '12210',
                        direction: 'W',
                        id: '1_12210',
                        lat: 47.640774,
                        locationType: 0,
                        lon: -122.278122,
                        name: 'E Mcgilvra St & 42nd Ave E',
                        routeIds: ['1_100009'],
                        wheelchairBoarding: 'UNKNOWN',
                    },
                    {
                        code: '13200',
                        direction: 'S',
                        id: '1_13200',
                        lat: 47.631897,
                        locationType: 0,
                        lon: -122.307327,
                        name: '19th Ave E & E Galer St',
                        routeIds: ['1_100018'],
                        wheelchairBoarding: 'UNKNOWN',
                    },
                    {
                        code: '12373',
                        direction: 'NE',
                        id: '1_12373',
                        lat: 47.616173,
                        locationType: 0,
                        lon: -122.308563,
                        name: 'E Madison St & 18th Ave',
                        routeIds: ['1_100009', '1_100018'],
                        wheelchairBoarding: 'UNKNOWN',
                    },
                    {
                        code: '13300',
                        direction: 'N',
                        id: '1_13300',
                        lat: 47.617145,
                        locationType: 0,
                        lon: -122.307304,
                        name: '19th Ave & E Madison St',
                        routeIds: ['1_100018'],
                        wheelchairBoarding: 'UNKNOWN',
                    },
                ],
                trips: [
                    {
                        blockId: '1_5593677',
                        directionId: '1',
                        id: '1_40552711',
                        routeId: '1_100009',
                        routeShortName: '',
                        serviceId: '1_12878',
                        shapeId: '1_20011004',
                        timeZone: '',
                        tripHeadsign: 'Downtown Seattle Via E Madison St',
                        tripShortName: 'LOCAL',
                    },
                    {
                        blockId: '1_5593677',
                        directionId: '0',
                        id: '1_40552671',
                        routeId: '1_100009',
                        routeShortName: '',
                        serviceId: '1_12878',
                        shapeId: '1_11011002',
                        timeZone: '',
                        tripHeadsign: 'Madison Park Via E Madison St',
                        tripShortName: 'LOCAL',
                    },
                    {
                        blockId: '1_5596577',
                        directionId: '1',
                        id: '1_44249598',
                        routeId: '1_100018',
                        routeShortName: '',
                        serviceId: '1_12878',
                        shapeId: '1_20012045',
                        timeZone: '',
                        tripHeadsign: 'Downtown Seattle Madison St',
                        tripShortName: 'LOCAL',
                    },
                ],
            },
        },
        text: 'OK',
        version: 2,
    },
};
