module.exports = {
    DEFAULT_ARRIVALS_AND_DEPARTURES_FOR_STOP_RESPONSE: {
        code: 200,
        currentTime: 1577651539187,
        data: {
            entry: {
                arrivalsAndDepartures: [
                    {
                        arrivalEnabled: true,
                        blockTripSequence: 0,
                        departureEnabled: true,
                        distanceFromStop: 2907.4400177688512,
                        frequency: null,
                        historicalOccupancy: '',
                        lastUpdateTime: 1577651457000,
                        numberOfStopsAway: 10,
                        predicted: true,
                        predictedArrivalInterval: null,
                        predictedArrivalTime: 1577651984000,
                        predictedDepartureInterval: null,
                        predictedDepartureTime: 1577651984000,
                        predictedOccupancy: '',
                        routeId: '1_100009',
                        routeLongName: '',
                        routeShortName: '11',
                        scheduledArrivalInterval: null,
                        scheduledArrivalTime: 1577651815000,
                        scheduledDepartureInterval: null,
                        scheduledDepartureTime: 1577651815000,
                        serviceDate: 1577606400000,
                        situationIds: [],
                        status: 'default',
                        stopId: '1_12353',
                        stopSequence: 15,
                        totalStopsInTrip: 24,
                        tripHeadsign: 'Downtown Seattle Via E Madison St',
                        tripId: '1_40552714',
                        tripStatus: {
                            activeTripId: '1_40552714',
                            blockTripSequence: 0,
                            closestStop: '1_12250',
                            closestStopTimeOffset: -1,
                            distanceAlongTrip: 747.3015589369256,
                            frequency: null,
                            lastKnownDistanceAlongTrip: 0,
                            lastKnownLocation: {
                                lat: 47.63458251953125,
                                lon: -122.27978515625,
                            },
                            lastKnownOrientation: 0,
                            lastLocationUpdateTime: 1577651457000,
                            lastUpdateTime: 1577651457000,
                            nextStop: '1_12260',
                            nextStopTimeOffset: 31,
                            orientation: 214.47921568745085,
                            phase: 'in_progress',
                            position: {
                                lat: 47.634556095785356,
                                lon: -122.27982736929499,
                            },
                            predicted: true,
                            scheduleDeviation: 169,
                            scheduledDistanceAlongTrip: 747.3015589369256,
                            serviceDate: 1577606400000,
                            situationIds: [],
                            status: 'SCHEDULED',
                            totalDistanceAlongTrip: 5616.782135766597,
                            vehicleId: '1_7030',
                        },
                        vehicleId: '1_7030',
                    },
                    {
                        arrivalEnabled: true,
                        blockTripSequence: 13,
                        departureEnabled: true,
                        distanceFromStop: 1726.8631166819105,
                        frequency: null,
                        historicalOccupancy: '',
                        lastUpdateTime: 1577651517000,
                        numberOfStopsAway: 9,
                        predicted: true,
                        predictedArrivalInterval: null,
                        predictedArrivalTime: 1577652357000,
                        predictedDepartureInterval: null,
                        predictedDepartureTime: 1577652357000,
                        predictedOccupancy: '',
                        routeId: '1_100018',
                        routeLongName: '',
                        routeShortName: '12',
                        scheduledArrivalInterval: null,
                        scheduledArrivalTime: 1577652357000,
                        scheduledDepartureInterval: null,
                        scheduledDepartureTime: 1577652357000,
                        serviceDate: 1577606400000,
                        situationIds: [],
                        status: 'default',
                        stopId: '1_12353',
                        stopSequence: 8,
                        totalStopsInTrip: 19,
                        tripHeadsign: 'Downtown Seattle Madison St',
                        tripId: '1_44249601',
                        tripStatus: {
                            activeTripId: '1_44249568',
                            blockTripSequence: 12,
                            closestStop: '1_13200',
                            closestStopTimeOffset: 1,
                            distanceAlongTrip: 4667.861433086713,
                            frequency: null,
                            lastKnownDistanceAlongTrip: 0,
                            lastKnownLocation: {
                                lat: 47.63199234008789,
                                lon: -122.3072280883789,
                            },
                            lastKnownOrientation: 0,
                            lastLocationUpdateTime: 1577651517000,
                            lastUpdateTime: 1577651517000,
                            nextStop: '1_13200',
                            nextStopTimeOffset: 1,
                            orientation: 270,
                            phase: 'in_progress',
                            position: {
                                lat: 47.63193525040586,
                                lon: -122.307236,
                            },
                            predicted: true,
                            scheduleDeviation: 778,
                            scheduledDistanceAlongTrip: 4667.861433086713,
                            serviceDate: 1577606400000,
                            situationIds: [],
                            status: 'SCHEDULED',
                            totalDistanceAlongTrip: 4672.11469083586,
                            vehicleId: '1_7140',
                        },
                        vehicleId: '1_7140',
                    },
                    {
                        arrivalEnabled: true,
                        blockTripSequence: 12,
                        departureEnabled: true,
                        distanceFromStop: 3654.741576705783,
                        frequency: null,
                        historicalOccupancy: '',
                        lastUpdateTime: 0,
                        numberOfStopsAway: 15,
                        predicted: false,
                        predictedArrivalInterval: null,
                        predictedArrivalTime: 0,
                        predictedDepartureInterval: null,
                        predictedDepartureTime: 0,
                        predictedOccupancy: '',
                        routeId: '1_100009',
                        routeLongName: '',
                        routeShortName: '11',
                        scheduledArrivalInterval: null,
                        scheduledArrivalTime: 1577653615000,
                        scheduledDepartureInterval: null,
                        scheduledDepartureTime: 1577653615000,
                        serviceDate: 1577606400000,
                        situationIds: [],
                        status: 'default',
                        stopId: '1_12353',
                        stopSequence: 15,
                        totalStopsInTrip: 24,
                        tripHeadsign: 'Downtown Seattle Via E Madison St',
                        tripId: '1_40552715',
                        tripStatus: {
                            activeTripId: '1_40552715',
                            blockTripSequence: 12,
                            closestStop: '1_12210',
                            closestStopTimeOffset: 657,
                            distanceAlongTrip: 0,
                            frequency: null,
                            lastKnownDistanceAlongTrip: 0,
                            lastKnownLocation: null,
                            lastKnownOrientation: 0,
                            lastLocationUpdateTime: 0,
                            lastUpdateTime: 0,
                            nextStop: '1_12210',
                            nextStopTimeOffset: 657,
                            orientation: 182.50313977983976,
                            phase: '',
                            position: {
                                lat: 47.640709,
                                lon: -122.278122,
                            },
                            predicted: false,
                            scheduleDeviation: 0,
                            scheduledDistanceAlongTrip: 0,
                            serviceDate: 1577606400000,
                            situationIds: [],
                            status: 'default',
                            totalDistanceAlongTrip: 5616.782135766597,
                            vehicleId: '',
                        },
                        vehicleId: '',
                    },
                    {
                        arrivalEnabled: true,
                        blockTripSequence: 14,
                        departureEnabled: true,
                        distanceFromStop: 2543.025398356236,
                        frequency: null,
                        historicalOccupancy: '',
                        lastUpdateTime: 1577652831000,
                        numberOfStopsAway: 13,
                        predicted: true,
                        predictedArrivalInterval: null,
                        predictedArrivalTime: 1577654157000,
                        predictedDepartureInterval: null,
                        predictedDepartureTime: 1577654157000,
                        predictedOccupancy: '',
                        routeId: '1_100018',
                        routeLongName: '',
                        routeShortName: '12',
                        scheduledArrivalInterval: null,
                        scheduledArrivalTime: 1577654157000,
                        scheduledDepartureInterval: null,
                        scheduledDepartureTime: 1577654157000,
                        serviceDate: 1577606400000,
                        situationIds: [],
                        status: 'default',
                        stopId: '1_12353',
                        stopSequence: 8,
                        totalStopsInTrip: 19,
                        tripHeadsign: 'Downtown Seattle Madison St',
                        tripId: '1_44249602',
                        tripStatus: {
                            activeTripId: '1_44249569',
                            blockTripSequence: 13,
                            closestStop: '1_13360',
                            closestStopTimeOffset: -7,
                            distanceAlongTrip: 3851.6991514123874,
                            frequency: null,
                            lastKnownDistanceAlongTrip: 0,
                            lastKnownLocation: {
                                lat: 47.62577819824219,
                                lon: -122.30731201171875,
                            },
                            lastKnownOrientation: 0,
                            lastLocationUpdateTime: 1577652831000,
                            lastUpdateTime: 1577652831000,
                            nextStop: '1_13370',
                            nextStopTimeOffset: 32,
                            orientation: 89.33428379151813,
                            phase: 'in_progress',
                            position: {
                                lat: 47.62575195254185,
                                lon: -122.30731675872137,
                            },
                            predicted: true,
                            scheduleDeviation: 473,
                            scheduledDistanceAlongTrip: 3851.6991514123874,
                            serviceDate: 1577606400000,
                            situationIds: [],
                            status: 'SCHEDULED',
                            totalDistanceAlongTrip: 4672.11469083586,
                            vehicleId: '1_7057',
                        },
                        vehicleId: '1_7057',
                    },
                ],
                nearbyStopIds: ['1_12373', '1_13300'],
                situationIds: [],
                stopId: '1_12353',
            },
            references: {
                agencies: [
                    {
                        disclaimer: '',
                        email: '',
                        fareUrl:
                            'http://metro.kingcounty.gov/tops/bus/fare/fare-info.html#fare_matrix',
                        id: '1',
                        lang: 'EN',
                        name: 'Metro Transit',
                        phone: '206-553-3000',
                        privateService: false,
                        timezone: 'America/Los_Angeles',
                        url: 'http://metro.kingcounty.gov',
                    },
                ],
                routes: [
                    {
                        agencyId: '1',
                        color: '',
                        description:
                            'Madison Park - Capitol Hill - Downtown Seattle',
                        id: '1_100009',
                        longName: '',
                        shortName: '11',
                        textColor: '',
                        type: 3,
                        url:
                            'http://metro.kingcounty.gov/schedules/011/n0.html',
                    },
                    {
                        agencyId: '1',
                        color: '',
                        description:
                            'Interlaken Park - First Hill - Downtown Seattle',
                        id: '1_100018',
                        longName: '',
                        shortName: '12',
                        textColor: '',
                        type: 3,
                        url:
                            'http://metro.kingcounty.gov/schedules/012/n0.html',
                    },
                ],
                situations: [],
                stops: [
                    {
                        code: '12353',
                        direction: 'SW',
                        id: '1_12353',
                        lat: 47.616619,
                        locationType: 0,
                        lon: -122.307877,
                        name: 'E Madison St & 19th Ave',
                        routeIds: ['1_100009', '1_100018'],
                        wheelchairBoarding: 'UNKNOWN',
                    },
                    {
                        code: '12250',
                        direction: 'SW',
                        id: '1_12250',
                        lat: 47.63464,
                        locationType: 0,
                        lon: -122.279846,
                        name: 'E Madison St & 41st Ave E',
                        routeIds: ['1_100009'],
                        wheelchairBoarding: 'UNKNOWN',
                    },
                    {
                        code: '12260',
                        direction: 'SW',
                        id: '1_12260',
                        lat: 47.633457,
                        locationType: 0,
                        lon: -122.281593,
                        name: 'E Madison St & E Garfield St',
                        routeIds: ['1_100009'],
                        wheelchairBoarding: 'UNKNOWN',
                    },
                    {
                        code: '13200',
                        direction: 'S',
                        id: '1_13200',
                        lat: 47.631897,
                        locationType: 0,
                        lon: -122.307327,
                        name: '19th Ave E & E Galer St',
                        routeIds: ['1_100018'],
                        wheelchairBoarding: 'UNKNOWN',
                    },
                    {
                        code: '12210',
                        direction: 'W',
                        id: '1_12210',
                        lat: 47.640774,
                        locationType: 0,
                        lon: -122.278122,
                        name: 'E Mcgilvra St & 42nd Ave E',
                        routeIds: ['1_100009'],
                        wheelchairBoarding: 'UNKNOWN',
                    },
                    {
                        code: '12373',
                        direction: 'NE',
                        id: '1_12373',
                        lat: 47.616173,
                        locationType: 0,
                        lon: -122.308563,
                        name: 'E Madison St & 18th Ave',
                        routeIds: ['1_100009', '1_100018'],
                        wheelchairBoarding: 'UNKNOWN',
                    },
                    {
                        code: '13300',
                        direction: 'N',
                        id: '1_13300',
                        lat: 47.617145,
                        locationType: 0,
                        lon: -122.307304,
                        name: '19th Ave & E Madison St',
                        routeIds: ['1_100018'],
                        wheelchairBoarding: 'UNKNOWN',
                    },
                ],
                trips: [
                    {
                        blockId: '1_5593679',
                        directionId: '1',
                        id: '1_40552714',
                        routeId: '1_100009',
                        routeShortName: '',
                        serviceId: '1_12878',
                        shapeId: '1_20011004',
                        timeZone: '',
                        tripHeadsign: 'Downtown Seattle Via E Madison St',
                        tripShortName: 'LOCAL',
                    },
                    {
                        blockId: '1_5596575',
                        directionId: '1',
                        id: '1_44249601',
                        routeId: '1_100018',
                        routeShortName: '',
                        serviceId: '1_12878',
                        shapeId: '1_20012045',
                        timeZone: '',
                        tripHeadsign: 'Downtown Seattle Madison St',
                        tripShortName: 'LOCAL',
                    },
                    {
                        blockId: '1_5596575',
                        directionId: '0',
                        id: '1_44249568',
                        routeId: '1_100018',
                        routeShortName: '',
                        serviceId: '1_12878',
                        shapeId: '1_11012041',
                        timeZone: '',
                        tripHeadsign: 'Interlaken Park Via 19th Ave',
                        tripShortName: 'LOCAL',
                    },
                    {
                        blockId: '1_5593678',
                        directionId: '1',
                        id: '1_40552715',
                        routeId: '1_100009',
                        routeShortName: '',
                        serviceId: '1_12878',
                        shapeId: '1_20011004',
                        timeZone: '',
                        tripHeadsign: 'Downtown Seattle Via E Madison St',
                        tripShortName: 'LOCAL',
                    },
                ],
            },
        },
        text: 'OK',
        version: 2,
    },
};
